[front]
front ansible_host=13.36.81.115

[back]
back ansible_host=10.0.2.186

[db]
db ansible_host=10.0.2.120

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/todo-key.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
postgres_user=postgres
postgres_password=niang@4693
postgres_db=todo_db
db_private_ip=10.0.2.120

[front:vars]
domain_name=medishop-todo.duckdns.org
admin_email=fatimatabintaniang8@gmail.com

; [back:vars]
; ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/.ssh/todo-key.pem -o StrictHostKeyChecking=no -W %h:%p ubuntu@13.36.81.115"'

; [db:vars]
; ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/.ssh/todo-key.pem -o StrictHostKeyChecking=no -W %h:%p ubuntu@13.36.81.115"'